# Generated by Django 3.0.1 on 2019-12-22 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20191222_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementstep',
            name='Exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise'),
            preserve_default=False,
        ),
    ]
