# Generated by Django 3.0.1 on 2020-03-18 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20200318_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=255), default=list, size=None),
        ),
    ]
